//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KampoClientWPF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoggerProducts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoggerProducts()
        {
            this.ChangeProductsList = new HashSet<ChangeProductsList>();
        }
    
        public int id_loggerProducts { get; set; }
        public string DateChanging { get; set; }
        public string TypeActionChanging { get; set; }
        public int productCategory_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChangeProductsList> ChangeProductsList { get; set; }
        public virtual ProductsCategory ProductsCategory { get; set; }
    }
}
