//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KampoClientWPF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogsUsers
    {
        public int id_logs { get; set; }
        public Nullable<int> user_id { get; set; }
        public string ActionType { get; set; }
        public string ObjectChanged { get; set; }
        public string NameObject { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
