//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KampoClientWPF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductReceipt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductReceipt()
        {
            this.ReceiptItems = new HashSet<ReceiptItems>();
        }
    
        public int id_productReceipt { get; set; }
        public Nullable<System.DateTime> DateReceipt { get; set; }
        public Nullable<int> order_id { get; set; }
    
        public virtual Orders Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceiptItems> ReceiptItems { get; set; }
    }
}
