//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KampoClientWPF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptItems
    {
        public int id_receiptItems { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> ProductCount { get; set; }
        public Nullable<int> productreceipt_id { get; set; }
    
        public virtual ProductReceipt ProductReceipt { get; set; }
        public virtual Products Products { get; set; }
    }
}
